# Site settings
title: 咀嚼之味
email: zry656565@gmail.com
description: >
  我是一名生活在上海的程序员，正在上海交通大学攻读软件工程硕士学位。
  我喜欢前端的技术、喜欢研究不同的编程语言之间的联系与差异，最爱的编程语言是 JavaScript，
  而我的梦想是成为一名独立游戏开发者。
baseurl: ""
url: "http://jerryzou.com"

#static images
local_url: "/assets/images"
#github source
#static_url: "/assets/images"
#upyun source
static_url: "http://jerryblog-image.b0.upaiyun.com/blog"
#qiniu source
qiniu_static_url: "http://jerryblog.qiniudn.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw]

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      duoshuo_comment: true
      release: true
